# Site settings
title: Justin's Website
email: jchaisetseree@albany.edu
description: Justin is a student at SUNY Albany
url: justinchaisetseree.github.io
github_username: justinchaisetseree

# Build settings
markdown: kramdown
permalink: pretty
